[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'elzr/vim-json'
[[plugins]]
repo = 'slim-template/vim-slim'
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neocomplete.vim'
[[plugins]]
repo = 'Shougo/neocomplcache'
[[plugins]]
repo = 'jwalton512/vim-blade'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'vim-syntastic/syntastic'
[[plugins]]
repo = 'scrooloose/nerdtree'


