[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'elzr/vim-json'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'vim-syntastic/syntastic'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
